name: "Make New Tagged Release"

on:
  push:
    tags:
      - "**"

jobs:
  tagged-release:
    name: "New Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0 # This is necessary to get the second latest tag

      - name: Get previous tag
        run: echo "::set-output name=tag::$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1))"
        id: previous_tag

      - name: Get current tag
        run: | 
          echo "::set-output name=tag::${GITHUB_REF#refs/*/}"
        id: current_tag

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            **Full Changelog**: https://github.com/${{ github.repository }}/compare/${{ steps.previous_tag.outputs.tag }}...${{ steps.current_tag.outputs.tag }}
          draft: false
          prerelease: false

  publish_pypi:
    name: Publish to PYPI
    needs: [tagged-release]
    runs-on: ubuntu-latest

    steps:
      # - name: Get artifacts
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: pypi_artifacts 

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ci.yml
          workflow_conclusion: success
          name: pypi_artifacts

      - name: Publish package
        if: startsWith(github.ref, 'refs/tags/')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          # repository_url: https://test.pypi.org/legacy/
          packages_dir: dist/
          verify_metadata: false
          verbose: true
          skip_existing: true